-- Robak Database Initialization Script (v1.0.0)
-- Orchestrates the loading of Robak's read-only reference data.
--
-- Reference only: MariaDB runs /docker-entrypoint-initdb.d ONLY on an empty data
-- directory. On the existing volume the data was imported manually (task P1-1).
-- The sourced files are generated by repo/docs/robak tools/csv_to_sql.py. Do not hand-edit.
USE `test_robak`;

-- 1. TABLE STRUCTURE (26 reference tables, ordered by foreign-key dependency)
SOURCE /docker-entrypoint-initdb.d/test_robak/001_reference_schema.sql;

-- 2. REFERENCE DATA (6970 rows: 1000 animals, 256 tracks, 40 board fields, 125 cards)
SOURCE /docker-entrypoint-initdb.d/test_robak/002_reference_seed.sql;
