-- Racer Database Initialization Script
-- Orchestrates the loading of Racer's read-only reference data.
--
-- Reference only: MariaDB runs /docker-entrypoint-initdb.d ONLY on an empty data
-- directory. On the existing volume the data must be applied manually (Phase 3 / R-2).
-- The sourced files are generated by repo/docs/racer tools/csv_to_sql.py from
-- reference-data/sql/V1__reference_schema.sql + V2__reference_seed.sql. Do not hand-edit.
--
-- In practice Flyway in racer-rest-api will own these migrations from P4-8 onward; this
-- file exists for a from-scratch rebuild, not for day-to-day use.
USE `test_racer`;

-- 1. TABLE STRUCTURE
SOURCE /docker-entrypoint-initdb.d/test_racer/001_reference_schema.sql;

-- 2. REFERENCE DATA (37 tables, 9,444 rows — includes 600 sponsors: verify with
--    `select count(*) from ref_sponsors` -> 600)
SOURCE /docker-entrypoint-initdb.d/test_racer/002_reference_seed.sql;
