-- Robak — reference schema (generated by tools/csv_to_sql.py; do not edit)
-- Read-only reference data. Runtime tables live in V3__runtime_schema.sql.

DROP TABLE IF EXISTS `tournament_rule`;
DROP TABLE IF EXISTS `tournament_rule_type`;
DROP TABLE IF EXISTS `rule`;
DROP TABLE IF EXISTS `cards_field`;
DROP TABLE IF EXISTS `cards_condition`;
DROP TABLE IF EXISTS `cards_player`;
DROP TABLE IF EXISTS `rule_duration`;
DROP TABLE IF EXISTS `rule_type`;
DROP TABLE IF EXISTS `player_scope`;
DROP TABLE IF EXISTS `card_type`;
DROP TABLE IF EXISTS `distribution_point_points_map`;
DROP TABLE IF EXISTS `board`;
DROP TABLE IF EXISTS `field_type`;
DROP TABLE IF EXISTS `track_regions_map`;
DROP TABLE IF EXISTS `track`;
DROP TABLE IF EXISTS `nationality`;
DROP TABLE IF EXISTS `continent`;
DROP TABLE IF EXISTS `region`;
DROP TABLE IF EXISTS `region_stat_distribution_point`;
DROP TABLE IF EXISTS `distribution_point`;
DROP TABLE IF EXISTS `distribution_point_type`;
DROP TABLE IF EXISTS `region_stat_terrain_map`;
DROP TABLE IF EXISTS `region_stat`;
DROP TABLE IF EXISTS `region_type`;
DROP TABLE IF EXISTS `terrain_type`;
DROP TABLE IF EXISTS `animal`;
DROP TABLE IF EXISTS `animal_subtype`;
DROP TABLE IF EXISTS `animal_type`;

CREATE TABLE `animal_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `animal_subtype` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `type_id` SMALLINT UNSIGNED NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_animal_subtype_type_id` FOREIGN KEY (`type_id`) REFERENCES `animal_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- name is the English common name (translations/animal_names.csv)
CREATE TABLE `animal` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `scientific_name` VARCHAR(128) NULL,
  `subtype_id` SMALLINT UNSIGNED NOT NULL,
  `price` SMALLINT UNSIGNED NOT NULL,
  `earth` TINYINT UNSIGNED NOT NULL,
  `water` TINYINT UNSIGNED NOT NULL,
  `air` TINYINT UNSIGNED NOT NULL,
  `forest` TINYINT UNSIGNED NOT NULL,
  `stamina` TINYINT UNSIGNED NOT NULL,
  `acceleration` TINYINT UNSIGNED NOT NULL,
  `speed` TINYINT UNSIGNED NOT NULL,
  `regeneration` TINYINT UNSIGNED NOT NULL,
  `total_terrain_points` SMALLINT UNSIGNED NOT NULL,
  `total_stats_points` SMALLINT UNSIGNED NOT NULL,
  `score` DECIMAL(6,2) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_animal_name` (`name`),
  CONSTRAINT `fk_animal_subtype_id` FOREIGN KEY (`subtype_id`) REFERENCES `animal_subtype` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The four flags are a bitmask over the elements
CREATE TABLE `terrain_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `earth` TINYINT UNSIGNED NOT NULL,
  `water` TINYINT UNSIGNED NOT NULL,
  `air` TINYINT UNSIGNED NOT NULL,
  `forest` TINYINT UNSIGNED NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `region_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `css_class_name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The altitude profile's shape, e.g. 'Climb LVL 2'
CREATE TABLE `region_stat` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- list_index 1..10 = the field's index within its sector; altitude -9.8..+9.8
CREATE TABLE `region_stat_terrain_map` (
  `region_stat_id` SMALLINT UNSIGNED NOT NULL,
  `list_index` TINYINT UNSIGNED NOT NULL,
  `altitude` DECIMAL(4,1) NOT NULL,
  PRIMARY KEY (`region_stat_id`, `list_index`),
  CONSTRAINT `fk_region_stat_terrain_map_region_stat_id` FOREIGN KEY (`region_stat_id`) REFERENCES `region_stat` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sprint / Hill — the two classifications
CREATE TABLE `distribution_point_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `distribution_point` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `type_id` SMALLINT UNSIGNED NOT NULL,
  `code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_distribution_point_type_id` FOREIGN KEY (`type_id`) REFERENCES `distribution_point_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Which category this region scores on which lap (laps 2,4,6,8,10)
CREATE TABLE `region_stat_distribution_point` (
  `region_stat_id` SMALLINT UNSIGNED NOT NULL,
  `lap` TINYINT UNSIGNED NOT NULL,
  `distribution_point_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`region_stat_id`, `lap`),
  CONSTRAINT `fk_region_stat_distribution_point_region_stat_id` FOREIGN KEY (`region_stat_id`) REFERENCES `region_stat` (`id`),
  CONSTRAINT `fk_region_stat_distribution_point_distribution_point_id` FOREIGN KEY (`distribution_point_id`) REFERENCES `distribution_point` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- An element + an altitude profile, laid over one sector
CREATE TABLE `region` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `map_id` TINYINT UNSIGNED NOT NULL,
  `region_type_id` SMALLINT UNSIGNED NOT NULL,
  `region_stat_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_region_region_type_id` FOREIGN KEY (`region_type_id`) REFERENCES `region_type` (`id`),
  CONSTRAINT `fk_region_region_stat_id` FOREIGN KEY (`region_stat_id`) REFERENCES `region_stat` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Named in Robak: the chess dump ships the ids only
CREATE TABLE `continent` (
  `id` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_continent_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ISO 3166-1 countries, copied from chess ref_nationality. code is alpha-3; continent_id is chess's region_id, renamed
CREATE TABLE `nationality` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` CHAR(3) NOT NULL,
  `continent_id` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_nationality_name` (`name`),
  UNIQUE KEY `uq_nationality_code` (`code`),
  CONSTRAINT `fk_nationality_continent_id` FOREIGN KEY (`continent_id`) REFERENCES `continent` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The country a track sits in — Robak owns its own copy, Nebula is not queried
CREATE TABLE `track` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `terrain_type_id` SMALLINT UNSIGNED NOT NULL,
  `location` VARCHAR(128) NOT NULL,
  `nationality_id` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_track_terrain_type_id` FOREIGN KEY (`terrain_type_id`) REFERENCES `terrain_type` (`id`),
  CONSTRAINT `fk_track_nationality_id` FOREIGN KEY (`nationality_id`) REFERENCES `nationality` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `track_regions_map` (
  `track_id` SMALLINT UNSIGNED NOT NULL,
  `sector_id` TINYINT UNSIGNED NOT NULL,
  `region_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`track_id`, `sector_id`),
  CONSTRAINT `fk_track_regions_map_track_id` FOREIGN KEY (`track_id`) REFERENCES `track` (`id`),
  CONSTRAINT `fk_track_regions_map_region_id` FOREIGN KEY (`region_id`) REFERENCES `region` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `field_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The fixed 40-field loop, ids 0..39, four sectors of ten
CREATE TABLE `board` (
  `id` TINYINT UNSIGNED NOT NULL,
  `sector_id` TINYINT UNSIGNED NOT NULL,
  `field_type_id` SMALLINT UNSIGNED NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_board_field_type_id` FOREIGN KEY (`field_type_id`) REFERENCES `field_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `distribution_point_points_map` (
  `distribution_point_id` SMALLINT UNSIGNED NOT NULL,
  `position` TINYINT UNSIGNED NOT NULL,
  `points` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`distribution_point_id`, `position`),
  CONSTRAINT `fk_distribution_point_points_map_distribution_point_id` FOREIGN KEY (`distribution_point_id`) REFERENCES `distribution_point` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Positive / Negative / Special / Neutral
CREATE TABLE `card_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Self / Behind / Above / Sector / All
CREATE TABLE `player_scope` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Flag / Surface / Weather / Condition
CREATE TABLE `rule_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Move / Region / Lap / Game
CREATE TABLE `rule_duration` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 100 cards. Negative resolve on draw; Positive/Special go to the hand
CREATE TABLE `cards_player` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `card_type_id` SMALLINT UNSIGNED NOT NULL,
  `player_scope_id` SMALLINT UNSIGNED NOT NULL,
  `rule_duration_id` SMALLINT UNSIGNED NOT NULL,
  `object_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cards_player_card_type_id` FOREIGN KEY (`card_type_id`) REFERENCES `card_type` (`id`),
  CONSTRAINT `fk_cards_player_player_scope_id` FOREIGN KEY (`player_scope_id`) REFERENCES `player_scope` (`id`),
  CONSTRAINT `fk_cards_player_rule_duration_id` FOREIGN KEY (`rule_duration_id`) REFERENCES `rule_duration` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 20 race-wide events. Always immediate, never held
CREATE TABLE `cards_condition` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `card_type_id` SMALLINT UNSIGNED NOT NULL,
  `player_scope_id` SMALLINT UNSIGNED NOT NULL,
  `rule_duration_id` SMALLINT UNSIGNED NOT NULL,
  `rule_type_id` SMALLINT UNSIGNED NOT NULL,
  `object_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cards_condition_card_type_id` FOREIGN KEY (`card_type_id`) REFERENCES `card_type` (`id`),
  CONSTRAINT `fk_cards_condition_player_scope_id` FOREIGN KEY (`player_scope_id`) REFERENCES `player_scope` (`id`),
  CONSTRAINT `fk_cards_condition_rule_duration_id` FOREIGN KEY (`rule_duration_id`) REFERENCES `rule_duration` (`id`),
  CONSTRAINT `fk_cards_condition_rule_type_id` FOREIGN KEY (`rule_type_id`) REFERENCES `rule_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The fixed effects of the special fields
CREATE TABLE `cards_field` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `card_type_id` SMALLINT UNSIGNED NOT NULL,
  `player_scope_id` SMALLINT UNSIGNED NOT NULL,
  `rule_duration_id` SMALLINT UNSIGNED NOT NULL,
  `object_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cards_field_card_type_id` FOREIGN KEY (`card_type_id`) REFERENCES `card_type` (`id`),
  CONSTRAINT `fk_cards_field_player_scope_id` FOREIGN KEY (`player_scope_id`) REFERENCES `player_scope` (`id`),
  CONSTRAINT `fk_cards_field_rule_duration_id` FOREIGN KEY (`rule_duration_id`) REFERENCES `rule_duration` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Global game rules, e.g. the 100-turn cap
CREATE TABLE `rule` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tournament_rule_type` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Deck policy: Single Stack / No Empty Stack / Return To Stack
CREATE TABLE `tournament_rule` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `rule_type_id` SMALLINT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tournament_rule_rule_type_id` FOREIGN KEY (`rule_type_id`) REFERENCES `tournament_rule_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
