events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  gzip          on;
  gzip_types    text/plain text/css application/javascript application/json image/svg+xml;

  server {
    listen 80;
    server_name _;

    location /chess/app/ {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri $uri/ /chess/app/index.html;
    }

    location /chess/app/assets/ {
      alias /usr/share/nginx/html/chess/app/assets/;
      expires 7d;
      access_log off;
      try_files $uri =404;
    }
  }
}
