-- Generated by tools/csv_to_sql.py from reference-data/. Do not edit by hand.

CREATE TABLE `ref_regions` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_nationalities` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_nationalities_region_id` FOREIGN KEY (`region_id`) REFERENCES `ref_regions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_genders` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_crew_employee_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_crew_members` (
  `id` BIGINT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `nationality_id` INT NOT NULL,
  `birth_date` DATE NOT NULL,
  `game_age` INT NOT NULL,
  `age_source` VARCHAR(16) NOT NULL,
  `historical` BOOLEAN NOT NULL,
  `gender_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_crew_members_nationality_id` FOREIGN KEY (`nationality_id`) REFERENCES `ref_nationalities` (`id`),
  CONSTRAINT `fk_ref_crew_members_gender_id` FOREIGN KEY (`gender_id`) REFERENCES `ref_genders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_crew_drivers` (
  `id` BIGINT NOT NULL,
  `trophies` INT NOT NULL,
  `total_races` INT NOT NULL,
  `wins` INT NOT NULL,
  `podiums` INT NOT NULL,
  `pole_positions` INT NOT NULL,
  `fastest_laps` INT NOT NULL,
  `win_ratio` DOUBLE NOT NULL,
  `win_in_row` INT NOT NULL,
  `average_finish` INT NOT NULL,
  `speed` FLOAT NOT NULL,
  `aerodynamic` FLOAT NOT NULL,
  `experience` FLOAT NOT NULL,
  `concentration` FLOAT NOT NULL,
  `overall_score` INT NOT NULL,
  `month_salary` INT NOT NULL,
  `elo_rating` DOUBLE NOT NULL,
  `elo_value` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_crew_drivers_id` FOREIGN KEY (`id`) REFERENCES `ref_crew_members` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_crew_employees` (
  `id` BIGINT NOT NULL,
  `experience` INT NOT NULL,
  `team_working` INT NOT NULL,
  `evolution` INT NOT NULL,
  `strategy` INT NOT NULL,
  `aerodynamic` INT NOT NULL,
  `pit_job` INT NOT NULL,
  `overall` INT NOT NULL,
  `month_salary` INT NOT NULL,
  `type_id` INT NOT NULL,
  `fictional` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_crew_employees_id` FOREIGN KEY (`id`) REFERENCES `ref_crew_members` (`id`),
  CONSTRAINT `fk_ref_crew_employees_type_id` FOREIGN KEY (`type_id`) REFERENCES `ref_crew_employee_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_racing_groups` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_racing_series` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `group_id` INT NOT NULL,
  `priority` INT NOT NULL,
  `grid_size` INT NOT NULL,
  `grid_size_source` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_racing_series_group_id` FOREIGN KEY (`group_id`) REFERENCES `ref_racing_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_racing_series_rank_points` (
  `id` BIGINT NOT NULL,
  `series_id` INT NOT NULL,
  `position` INT NOT NULL,
  `points` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_racing_series_rank_points_series_id` FOREIGN KEY (`series_id`) REFERENCES `ref_racing_series` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_point_systems` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `pole_position` BOOLEAN NOT NULL,
  `fastest_lap` BOOLEAN NOT NULL,
  `lap_on_lead` BOOLEAN NOT NULL,
  `most_lead_laps` BOOLEAN NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_point_systems_group_id` FOREIGN KEY (`group_id`) REFERENCES `ref_racing_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_point_system_to_positions` (
  `id` INT NOT NULL,
  `point_system_id` INT NOT NULL,
  `position` INT NOT NULL,
  `points` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_point_system_to_positions_point_system_id` FOREIGN KEY (`point_system_id`) REFERENCES `ref_point_systems` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_sponsor_groups` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `unlock_metric` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_sponsor_families` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `group_id` INT NOT NULL,
  `level` INT NOT NULL,
  `unlock_threshold` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_sponsor_families_group_id` FOREIGN KEY (`group_id`) REFERENCES `ref_sponsor_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_sponsors` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(64) NOT NULL,
  `family_id` INT NOT NULL,
  `season_salary` BIGINT NOT NULL,
  `bonus_salary` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_sponsors_family_id` FOREIGN KEY (`family_id`) REFERENCES `ref_sponsor_families` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_circuit_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_locations` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `nationality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_locations_nationality_id` FOREIGN KEY (`nationality_id`) REFERENCES `ref_nationalities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_circuits` (
  `id` INT NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `location_id` INT NOT NULL,
  `circuit_type_id` INT NOT NULL,
  `circuit_type_source` VARCHAR(8) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `geocode_source` VARCHAR(11) NOT NULL,
  `circuit_source` VARCHAR(8) NOT NULL,
  `lap_length_m` INT NOT NULL,
  `lap_length_source` VARCHAR(12) NOT NULL,
  `map_image` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_circuits_location_id` FOREIGN KEY (`location_id`) REFERENCES `ref_locations` (`id`),
  CONSTRAINT `fk_ref_circuits_circuit_type_id` FOREIGN KEY (`circuit_type_id`) REFERENCES `ref_circuit_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_circuit_racing_groups` (
  `circuit_id` INT NOT NULL,
  `racing_group_id` INT NOT NULL,
  `group_index` INT NOT NULL,
  PRIMARY KEY (`circuit_id`, `racing_group_id`),
  CONSTRAINT `fk_ref_circuit_racing_groups_circuit_id` FOREIGN KEY (`circuit_id`) REFERENCES `ref_circuits` (`id`),
  CONSTRAINT `fk_ref_circuit_racing_groups_racing_group_id` FOREIGN KEY (`racing_group_id`) REFERENCES `ref_racing_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_cup_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `racing_group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_cup_types_racing_group_id` FOREIGN KEY (`racing_group_id`) REFERENCES `ref_racing_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_cups` (
  `id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `cup_type_id` INT NOT NULL,
  `racing_group_id` INT NOT NULL,
  `point_system_id` INT NOT NULL,
  `year` INT NOT NULL,
  `is_real` BOOLEAN NOT NULL,
  `stages` INT NOT NULL,
  `unlocks` VARCHAR(64) NULL,
  `entry_privilege` INT NOT NULL,
  `allow_restart` BOOLEAN NOT NULL,
  `entry_fee` INT NOT NULL,
  `prize_pool` INT NOT NULL,
  `entry_prestige` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_cups_cup_type_id` FOREIGN KEY (`cup_type_id`) REFERENCES `ref_cup_types` (`id`),
  CONSTRAINT `fk_ref_cups_racing_group_id` FOREIGN KEY (`racing_group_id`) REFERENCES `ref_racing_groups` (`id`),
  CONSTRAINT `fk_ref_cups_point_system_id` FOREIGN KEY (`point_system_id`) REFERENCES `ref_point_systems` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_grand_prix` (
  `id` INT NOT NULL,
  `cup_id` INT NOT NULL,
  `round` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `circuit_id` INT NOT NULL,
  `event_date` DATE NOT NULL,
  `event_date_source` VARCHAR(12) NOT NULL,
  `format` VARCHAR(12) NOT NULL,
  `laps` INT NOT NULL,
  `laps_source` VARCHAR(12) NOT NULL,
  `total_distance_m` INT NOT NULL,
  `time_limit_min` INT NOT NULL,
  `drivers_per_car` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_grand_prix_cup_id` FOREIGN KEY (`cup_id`) REFERENCES `ref_cups` (`id`),
  CONSTRAINT `fk_ref_grand_prix_circuit_id` FOREIGN KEY (`circuit_id`) REFERENCES `ref_circuits` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_cup_unlocks` (
  `cup_id` INT NOT NULL,
  `unlocks_cup_id` INT NOT NULL,
  `condition` VARCHAR(12) NOT NULL,
  `rungs` INT NOT NULL,
  `edge_source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`cup_id`, `unlocks_cup_id`),
  CONSTRAINT `fk_ref_cup_unlocks_cup_id` FOREIGN KEY (`cup_id`) REFERENCES `ref_cups` (`id`),
  CONSTRAINT `fk_ref_cup_unlocks_unlocks_cup_id` FOREIGN KEY (`unlocks_cup_id`) REFERENCES `ref_cups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_car_brands` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `nationality_id` INT NOT NULL,
  `founded_year` INT NOT NULL,
  `brand_source` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_car_brands_nationality_id` FOREIGN KEY (`nationality_id`) REFERENCES `ref_nationalities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_cars` (
  `id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `brand_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  `series_source` VARCHAR(8) NOT NULL,
  `model_year` INT NULL,
  `horsepower` INT NOT NULL,
  `weight_kg` INT NOT NULL,
  `drivetrain` VARCHAR(4) NOT NULL,
  `base_price` INT NOT NULL,
  `data_source` VARCHAR(14) NOT NULL,
  `top_speed` INT NOT NULL,
  `acceleration` INT NOT NULL,
  `aerodynamic` INT NOT NULL,
  `grip` INT NOT NULL,
  `reliability` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_cars_brand_id` FOREIGN KEY (`brand_id`) REFERENCES `ref_car_brands` (`id`),
  CONSTRAINT `fk_ref_cars_series_id` FOREIGN KEY (`series_id`) REFERENCES `ref_racing_series` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_circuit_sectors` (
  `circuit_id` INT NOT NULL,
  `sector` INT NOT NULL,
  `share` DECIMAL(4,3) NOT NULL,
  `character` VARCHAR(9) NOT NULL,
  `overtaking` DECIMAL(4,3) NOT NULL,
  `tyre_load` DECIMAL(4,3) NOT NULL,
  `fuel_load` DECIMAL(4,3) NOT NULL,
  `sector_source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`circuit_id`, `sector`),
  CONSTRAINT `fk_ref_circuit_sectors_circuit_id` FOREIGN KEY (`circuit_id`) REFERENCES `ref_circuits` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_rally_stages` (
  `grand_prix_id` INT NOT NULL,
  `stage` INT NOT NULL,
  `road` INT NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `length_m` INT NOT NULL,
  `surface` VARCHAR(6) NOT NULL,
  `surface_source` VARCHAR(7) NOT NULL,
  `is_power_stage` BOOLEAN NOT NULL,
  PRIMARY KEY (`grand_prix_id`, `stage`),
  CONSTRAINT `fk_ref_rally_stages_grand_prix_id` FOREIGN KEY (`grand_prix_id`) REFERENCES `ref_grand_prix` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `economy_constants` (
  `key` VARCHAR(42) NOT NULL,
  `difficulty_scope` VARCHAR(6) NOT NULL,
  `value` VARCHAR(34) NOT NULL,
  `value_type` VARCHAR(7) NOT NULL,
  `source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`key`, `difficulty_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_achievements` (
  `id` INT NOT NULL,
  `code` VARCHAR(28) NOT NULL,
  `category` VARCHAR(12) NOT NULL,
  `name` VARCHAR(24) NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `tier` VARCHAR(8) NOT NULL,
  `points` INT NOT NULL,
  `requires_hard` BOOLEAN NOT NULL,
  `trigger_type` VARCHAR(9) NOT NULL,
  `trigger_json` VARCHAR(400) NOT NULL,
  `trigger_source` VARCHAR(7) NOT NULL,
  `icon` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_tyres` (
  `id` INT NOT NULL,
  `construction` VARCHAR(12) NOT NULL,
  `compound` VARCHAR(6) NOT NULL,
  `series_scope` VARCHAR(7) NOT NULL,
  `peak_grip` DECIMAL(5,4) NOT NULL,
  `base_wear` DECIMAL(5,4) NOT NULL,
  `wet_grip` DECIMAL(5,4) NOT NULL,
  `wet_wear` DECIMAL(5,4) NOT NULL,
  `surface_grip_json` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_upgrades` (
  `slot` VARCHAR(11) NOT NULL,
  `level` INT NOT NULL,
  `cost_factor` DECIMAL(6,5) NOT NULL,
  `effect_json` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`slot`, `level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_strategy_cards` (
  `id` INT NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `context` VARCHAR(18) NOT NULL,
  `energy` INT NOT NULL,
  `cooldown_steps` INT NOT NULL,
  `once_per_session` BOOLEAN NOT NULL,
  `rarity` VARCHAR(8) NOT NULL,
  `effect_json` VARCHAR(160) NOT NULL,
  `card_source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_lap_event_cards` (
  `id` INT NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `scope` VARCHAR(9) NOT NULL,
  `base_weight` DECIMAL(5,4) NOT NULL,
  `delta_min_ms` INT NOT NULL,
  `delta_max_ms` INT NOT NULL,
  `is_incident_draw` BOOLEAN NOT NULL,
  `weight_modifiers_json` VARCHAR(160) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_race_incidents` (
  `id` INT NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(24) NOT NULL,
  `severity` INT NOT NULL,
  `base_probability` DECIMAL(6,5) NOT NULL,
  `raised_by` VARCHAR(9) NOT NULL,
  `applies_to` VARCHAR(7) NOT NULL,
  `is_terminal` BOOLEAN NOT NULL,
  `effect_json` VARCHAR(160) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_coupons` (
  `id` INT NOT NULL,
  `code` VARCHAR(14) NOT NULL,
  `reward_type` VARCHAR(16) NOT NULL,
  `reward_json` VARCHAR(160) NOT NULL,
  `max_redemptions` INT NOT NULL,
  `redemptions_used` INT NOT NULL,
  `per_save_limit` INT NOT NULL,
  `valid_from` DATE NOT NULL,
  `expires_at` DATE NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_commentary_templates` (
  `id` INT NOT NULL,
  `event_type` VARCHAR(24) NOT NULL,
  `template` VARCHAR(140) NOT NULL,
  `weight` DECIMAL(5,4) NOT NULL,
  `interest_score` INT NOT NULL,
  `scope` VARCHAR(7) NOT NULL,
  `template_source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_privilege_rank_points` (
  `id` INT NOT NULL,
  `rank_from` INT NOT NULL,
  `rank_to` INT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_sponsor_objectives` (
  `id` INT NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `scope` VARCHAR(6) NOT NULL,
  `group_bias` VARCHAR(20) NOT NULL,
  `min_level` INT NOT NULL,
  `condition_json` VARCHAR(120) NOT NULL,
  `payout_factor` DECIMAL(3,1) NOT NULL,
  `objective_source` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_federation_awards` (
  `id` INT NOT NULL,
  `series_tier` INT NOT NULL,
  `award_type` VARCHAR(12) NOT NULL,
  `scope` VARCHAR(6) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ref_federation_awards_series_tier` FOREIGN KEY (`series_tier`) REFERENCES `ref_racing_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ref_driver_name_banks` (
  `nationality_id` INT NOT NULL,
  `kind` VARCHAR(6) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `weight` INT NOT NULL,
  PRIMARY KEY (`nationality_id`, `kind`, `name`),
  CONSTRAINT `fk_ref_driver_name_banks_nationality_id` FOREIGN KEY (`nationality_id`) REFERENCES `ref_nationalities` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
