-- enum types
create type difficulty as enum ('EASY', 'MEDIUM', 'HARD');
alter type difficulty owner to hacman;

create type gallery_subtype_enum as enum (
        'Subtype 1', 'Subtype 2', 'Subtype 3', 'Subtype 4', 'Subtype 5',
        'Subtype 6', 'Subtype 7', 'Subtype 8', 'Subtype 9', 'Subtype 10',
        'Subtype 11'
    );
alter type gallery_subtype_enum owner to hacman;

create type gallery_theme_enum as enum (
        'Theme 1', 'Theme 2', 'Theme 3', 'Theme 4', 'Theme 5', 'Theme 6',
        'Theme 7', 'Theme 8', 'Theme 9', 'Theme 10', 'Theme 11', 'Theme 12',
        'Theme 13', 'Theme 14', 'Theme 15', 'Theme 16', 'Theme 17', 'Theme 18',
        'Theme 19', 'Theme 20', 'Theme 21', 'Theme 22', 'Theme 23',
        'Theme 24', 'Theme 25', 'Theme 26', 'Theme 27', 'Theme 28',
        'Theme 29', 'Theme 30', 'Theme 31', 'Theme 32', 'Theme 33', 'Theme 34',
        'Theme 35', 'Theme 36', 'Theme 37', 'Theme 38', 'Theme 39', 'Theme 40',
        'Theme 41', 'Theme 42', 'Theme 43', 'Theme 44', 'Theme 45', 'Theme 46',
        'Theme 47', 'Theme 48', 'Theme 49', 'Theme 50', 'Theme 51',
        'Theme 52', 'Theme 53', 'Theme 54', 'Theme 55', 'Theme 56', 'Theme 57',
        'Theme 58', 'Theme 59', 'Theme 60', 'Theme 61', 'Theme 62',
        'Theme 63', 'Theme 64', 'Theme 65', 'Theme 66', 'Theme 67',
        'Theme 68', 'Theme 69', 'Theme 70', 'Theme 71', 'Theme 72',
        'Theme 73', 'Theme 74', 'Theme 75', 'Theme 76', 'Theme 77',
        'Theme 78', 'Theme 79', 'Theme 80', 'Theme 81', 'Theme 82',
        'Theme 83', 'Theme 84', 'Theme 85', 'Theme 86', 'Theme 87',
        'Theme 88', 'Theme 89', 'Theme 90', 'Theme 91', 'Theme 92',
        'Theme 93', 'Theme 94', 'Theme 95', 'Theme 96', 'Theme 97',
        'Theme 98', 'Theme 99', 'Theme 100', 'Theme 101', 'Theme 102', 'Theme 103',
        'Theme 104', 'Theme 105', 'Theme 106', 'Theme 107', 'Theme 108',
        'Theme 109', 'Theme 110', 'Theme 111', 'Theme 112', 'Theme 113', 'Theme 114',
        'Theme 115', 'Theme 116', 'Theme 117', 'Theme 118', 'Theme 119',
        'Theme 120', 'Theme 121', 'Theme 122', 'Theme 123', 'Theme 124', 'Theme 125',
        'Theme 126', 'Theme 127', 'Theme 128', 'Theme 129', 'Theme 130',
        'Theme 131'
    );
alter type gallery_theme_enum owner to hacman;

create type gallery_type_enum as enum (
        'Type 1', 'Type 2', 'Type 3', 'Type 4', 'Type 5', 'Type 6',
        'Type 7', 'Type 8', 'Type 9', 'Type 10', 'Type 11'
    );
alter type gallery_type_enum owner to hacman;

-- sequence for `level` column
create sequence galleries_level_seq1;
alter sequence galleries_level_seq1 owner to hacman;

-- `users` table
create table users
(
    id               uuid        default gen_random_uuid() not null primary key,
    external_auth_id text unique,
    username         text                                  not null unique,
    email            text                                  not null unique,
    created_at       timestamptz default now()             not null,
    updated_at       timestamptz default now()             not null
);
alter table users owner to hacman;

-- `galleries` table
create table galleries
(
    id          uuid        default gen_random_uuid()                         not null primary key,
    title       text                                                          not null,
    description text,
    image_count integer     default 10                                        not null,
    created_at  timestamptz default now()                                     not null,
    gallery_id  integer generated by default as identity (maxvalue 999),
    theme       gallery_theme_enum                                            not null,
    type        gallery_type_enum                                             not null,
    subtype     gallery_subtype_enum                                          not null,
    level       integer     default nextval('galleries_level_seq1'::regclass) not null
);
alter table galleries owner to hacman;

-- `user_galleries` table
create table user_galleries
(
    id           uuid        default gen_random_uuid() not null primary key,
    user_id      uuid                                  not null
        references users on delete cascade,
    gallery_id   uuid                                  not null
        references galleries on delete cascade,
    is_unlocked  boolean     default false             not null,
    unlocked_at  timestamptz,
    best_time_ms bigint,
    best_time_at timestamptz,
    created_at   timestamptz default now()             not null,
    updated_at   timestamptz default now()             not null,
    constraint uq_user_gallery unique (user_id, gallery_id)
);
alter table user_galleries owner to hacman;

create index idx_user_galleries_user
    on user_galleries (user_id);

create index idx_user_galleries_gallery
    on user_galleries (gallery_id);